### ISSUE TITLE
Changing driver of daemon not effective

### ISSUE THREAD

**Issue by brightbulbnz** [rancher/convoy#103]
It seems that convoy creates a .cfg file when first run. 
If you later change the driver in your daemon call, the change is not made as shown by `convoy info`. Observe:

`root@web:~$ ps aux | grep convoy
root      1515  0.0  0.0 181228 10552 ?        Sl   16:24   0:00 /usr/local/bin/convoy --socket=/var/run/convoy/convoy.sock daemon --drivers devicemapper --driver-opts dm.datadev=/dev/sdb1 --driver-opts dm.metadatadev=/dev/sdb2 --ignore-docker-delete`

`root@web:/var/lib/convoy# cat convoy.cfg
{"Root":"/var/lib/convoy","DriverList":["vfs"],"DefaultDriver":"vfs","MountNamespaceFD":"","IgnoreDockerDelete":false}`

`root@web:~$ convoy info
{
"General": {
        "Root": "/var/lib/convoy",
        "DriverList": [
                "vfs"
        ],
        "DefaultDriver": "vfs",
        "MountNamespaceFD": "",
        "IgnoreDockerDelete": false
},
"vfs": {
        "DefaultVolumeSize": "107374182400",
        "Path": "/mnt/docker_volume/",
        "Root": "/var/lib/convoy/vfs"
}
}`

**Comment by yasker** [comment]
Hi @brightbulbnz 

We've merged #120 , with new `--ignore-config-file` option, you should able to change driver on the fly, as long as that driver doesn't exist yet. Simply start the daemon with `--ignore-config-file`.

Thanks.
