### ISSUE TITLE
Command line options for daemon not effective after first run

### ISSUE THREAD

**Issue by jinuxstyle** [rancher/convoy#108]
Convoy saves command lines to configure files for the first successful run, and later on when user starts the daemon again with different command line options, convoy will ignore the new command line if it finds configure files for the daemon. This causes problems like #103 and #94.

**Comment by jinuxstyle** [comment]
I submitted a patch for this problem in pull request #95, but it turns out not be a thorough thorough solution as @yasker commented.

After analyzing the three types of configure files including general, driver and volume configure files, I'd like to propose another solution which is actually an improvement of the previous one. It has following main points:
1. Still add the ignore-config-file option for expressing user's intention to change command line options.
2. With the option specified, convoy should and could ignore the general configure file named convoy.cfg because it would not affect existing volumes. For the driver and volume configure files, convoy should ignore them only when there is no volume for the driver user specified in the new command line. In other words, if there is no volume for a driver, user can change the driver options without problem.

Comments?

**Comment by yasker** [comment]
Merged #120, this one can be closed.
