### ISSUE TITLE
Convoy in a mesos cluster- How to move volume with containers to different machine?

### ISSUE THREAD

**Issue by gufranmmu** [rancher/convoy#122]
So, i have two slaves both of convoy service running.

If i execute: ```sudo docker run -it -v testvolume:/testvolume --volume-driver=convoy ubuntu ```in slave 1, It creates testvolume and attach it to the container.

But, if i now execute the same command in slave 2, it creates another volume of the same name, but different id

How can i move volume with container from machine to machine using convoy?

**Comment by yasker** [comment]
You can use NFS, mount the NFS to the convoy managed volume directory(`vfs.path`), then you can use the same volume by indicate the same volume name between hosts.
