### ISSUE TITLE
How to move volume to a different host with the container without bakcup/snapshot?

### ISSUE THREAD

**Issue by gufranmmu** [rancher/convoy#125]
I just tested this and noticed that convoy does not mount that original volume to a different host. It creates a new volume.

Executing this command creates an EBS volume in host1 and removes the container, but the volume is still attached to the host. Convoy doesn't seem to detach the volume from the host.
sudo docker run -d -v testvol:/testvolume --volume-driver=convoy ubuntu

And executing that same command now in host2 creates a new volume :(

How to move volume to a different host with the container without creating backup or snapshot?

**Comment by yasker** [comment]
Duplicate with #135
