### ISSUE TITLE
Running Convoy EBS on RancherOS

### ISSUE THREAD

**Issue by saphoooo** [rancher/convoy#128]
[rancher@ip-10-0-0-12 ~]$ ros -v
**ros version v0.4.5**
[rancher@ip-10-0-0-12 ~]$ sudo convoy -v
**convoy version 0.3**

I've followed the instructions provided on this git to install convoy on my AWS instance running RancherOS.
But, when I try to create a volume, I've the following error:

```
[rancher@ip-10-0-0-12 ~]$ sudo convoy create my_vol
ERRO[0010] Error response from server, Failed to execute: mkfs [-t ext4 /dev/xvdk], output , error exec: "mkfs": executable file not found in $PATH

{
        "Error": "Error response from server, Failed to execute: mkfs [-t ext4 /dev/xvdk], output , error exec: \"mkfs\": executable file not found in $PATH\n"
}
```

I've a workaround which consist to alias mkfs:

```
[rancher@ip-10-0-0-12 ~]$ sudo ln -s /sbin/mkfs.ext4 /sbin/mkfs
[rancher@ip-10-0-0-12 ~]$ sudo convoy create my_vol3
721a9fb3-5f9d-4c89-b58e-da02f64b8f1b
```

But it's not much pretty.

**Comment by saphoooo** [comment]
Furthermore, sudo convoy list always return an empty list, even if some volume were created.

**Comment by mathuin** [comment]
I've just started with Convoy and EBS on RancherOS.  I use the symlink you mentioned (thank you!) but I get the right answer when running `sudo convoy list`.

```
[rancher@awshost1 ~]$ ros -v
ros version v0.4.5
[rancher@awshost1 ~]$ sudo convoy -v
convoy version 0.4.3
```

My convoy's newer, so I bet they fixed the list issue you mentioned.

**Comment by saphoooo** [comment]
@mathuin You means there is some improvement, great! I'll upgrade to the new version and check what's new :)
