### ISSUE TITLE
`docker volume ls` does not show Convoy volumes

### ISSUE THREAD

**Issue by mathuin** [rancher/convoy#131]
When I run the following command, I expect to see a list of all volumes, both local and convoy.

```
[rancher@awshost1 ~]$ docker volume ls
list convoy: VolumeDriver.List: Handler not found: POST /VolumeDriver.List
DRIVER              VOLUME NAME
local               a42437602af71818a62bddf23d7f7c0244f50f21250a1d4a6cecfafddf758b11
```

The convoy daemon log had these entries as a result of running the above command:

```
DEBU[0510] Response:  {
	"Implements": [
		"VolumeDriver"
	]
}  pkg=daemon
ERRO[0510] Handler not found: POST /VolumeDriver.List    pkg=daemon
```

The logic is already there with `convoy list`, it's a simple matter of making another POST handler to support the other command.

**Comment by yasker** [comment]
Please try again with latest v0.5.0-rc1, it should work.
