### ISSUE TITLE
Sharing a volume between containers?

### ISSUE THREAD

**Issue by Mirabis** [rancher/convoy#141]
Is there any way to specify a convoy drive:

```
config
```
and mount as:
```
config\app1\conf:/config
config\app2\conf:/config
```
?

I'm currently using Rancher + GlusterFS + Convoy GlusterFS .. but don;t see a a way to do that...

**Comment by yasker** [comment]
Please use `convoy-nfs` instead in Rancher, it can share volume between containers, with specified volume name.
