### ISSUE TITLE
Convoy glusterfs driver didn't remove volume when use "docker volume rm <volume-name>"

### ISSUE THREAD

**Issue by sak0** [rancher/convoy#145]
**daemon/docker.go**

`

request := &api.VolumeDeleteRequest{

                        VolumeName: volume.Name,

			// By default we don't want to remove the volume because probably we're using NFS

			ReferenceOnly: true,

		}

`

so, when i use "**docker volume rm volume volume-0c76ed1c8201494a**" 
directory and files like "/var/lib/rancher/convoy/glusterfs/mounts/vol1/volume-0c76ed1c8201494a/*" will leave over, 

this will be improvment?

**Comment by yasker** [comment]
It's intended because for NFS(which is most of our use case) we don't want to delete user data, unless user ask us to do it. User is likely want to share volume between containers. Otherwise an accidental `docker rm -v` will destroy data suppose to be persistent.
