### ISSUE TITLE
Coudln't get flock. Error: permission denied

### ISSUE THREAD

**Issue by akamalov** [rancher/convoy#147]
**Environment:**

```
Convoy: Convoy v0.5.0-rc1 release
Docker: 1.12.0
OS: RHEL 7.2
```

Trying to create volume using `docker volume create --driver=convoy`, and getting an error:

```
[root@node1 plugins]# docker volume create --driver=convoy --name=test1 --opt=size=1
Error response from daemon: create test1: Coudln't get flock. Error: permission denied
[root@node1 plugins]# ls -ld /var/run/convoy/convoy.sock 
srwxr-xr-x 1 root root 0 Aug  1 10:47 /var/run/convoy/convoy.sock
[root@node1 plugins]# 
```

This used to work under 0..4.3. Problem exhibited itself port upgrade to 0.5.0-rc1.

Played around a little bit. Compared to REX-Ray which creates a socket under `/run/docker/plugins` directory.  Modified my systemd convoy service to have:

```
ExecStart=/usr/local/bin/convoy --socket unix:///run/docker/plugins/convoy.sock daemon --drivers vfs  --driver-opts vfs.path=/mnt/nfs
```

However, when attempting to create a volume via docker, got error:

```
[root@node1 ~]# docker volume create --driver=convoy --name=test1 --opt=size=1
Error response from daemon: create test1: Post http://%2Fvar%2Frun%2Fconvoy%2Fconvoy.sock/VolumeDriver.Create: dial unix /var/run/convoy/convoy.sock: connect: no such file or directory
[root@node1 ~]# 
```

Hmmm... My `/etc/docker/plugins/convoy.spec` looks like this:

```
unix:///run/convoy/convoy.sock
```

...and I have deleted `/var/lib/rancher/convoy` directory prior to restarting Convoy service, but it looks like convoy is still passing `/var/run/convoy/convoy.sock` for the socket location.

**Comment by yasker** [comment]
What does `convoy info` say? Is the daemon running?

**Comment by akamalov** [comment]
It's up:

```
[root@mslave5 purestorage-flocker-driver]# convoy info
{
"General": {
        "Root": "/var/lib/rancher/convoy",
        "DriverList": [
                "vfs"
        ],
        "DefaultDriver": "vfs",
        "MountNamespaceFD": "",
        "IgnoreDockerDelete": false
},
"vfs": {
        "DefaultVolumeSize": "107374182400",
        "Path": "/mnt/nfs",
        "Root": "/var/lib/rancher/convoy/vfs"
}
}
[root@mslave5 purestorage-flocker-driver]# 

```

**Comment by yasker** [comment]
In fact, don't touch the plugin directory...

It's likely Docker has some permission trouble to get to the directory, is docker daemon has enough privilege to visit `/var/run/convoy/convoy.sock`

**Comment by akamalov** [comment]
Thanks @yasker . Docker running as ```root```, no ```usernsremap``` implemented, so I wonder why wouldn't have proper permissions ?

**Comment by yasker** [comment]
I realize it may complains about flock in VFS path rather than Convoy itself.

In 0.5.0 we move the VFS configuration to `vfs.path`, in order to share across the hosts. If the path is mounted as NFS, then flock need to be supported in NFS.

**Comment by yasker** [comment]
So, can you try if `convoy create` works?

**Comment by rafagsiqueira** [comment]
I am having the same issue. And convoy create gives the following error:
ERRO[0000] Error response from server, Coudln't get flock. Error: open /data/config/vfs_volume_nelly_vol.json.lock: no such file or directory
 
{
	"Error": "Error response from server, Coudln't get flock. Error: open /data/config/vfs_volume_nelly_vol.json.lock: no such file or directory\n"
}

/data is mounted using nfs.

**Comment by jzhoucliqr** [comment]
@rafagsiqueira  Seen the same error, in my case it's because the /data/config directory is missing, which is because I was trying to mount from multiple nfs places.

**Comment by rafagsiqueira** [comment]
@jzhoucliqr After creating the /data/config directory it worked for me. Thanks a lot!
