### ISSUE TITLE
Removing Docker volume doesn't remove underlying folder in vfs.path

### ISSUE THREAD

**Issue by jpapejr** [rancher/convoy#150]
convoy: v0.5.0-rc1 release
docker: 1.12.0

1. docker volume create -d convoy --name test.1
2. docker volume ls (shows new volume, yay!)
3. docker volume rm test.1
4. docker volume ls (shows volume is no more... or is it?)
...
ssh into machine with NFS mount (vfs.path) and lo, test.1 directory exists still and must be removed manually. 

Is this expected?

**Comment by jpapejr** [comment]
Logging into that same Docker host and using `sudo  convoy delete test.1` removed the directory from the vfs.path as expected. It also correctly removes it from the `docker volume ls` listing. So convoy itself, is working.

**Comment by yasker** [comment]
For docker call of deletion of volume(though docker volume plugin interface), we avoided deletion of the directory because user may want to reuse it, e.g. in the case of shared nfs volume.

In Convoy, the deletion is done automatically and can be avoid by `--reference` flag.
