### ISSUE TITLE
Command line options not obeyed

### ISSUE THREAD

**Issue by mklatsky** [rancher/convoy#16]
Running 'convoy daemon --drivers devicemapper --driver-opts dm.datadev=/dev/loop5 --driver-opts dm.metadatadev=/dev/loop6' per the initial docs for the first time does not daemonize convoy. 

A config file is written to /var/lib/convoy/convoy.cfg. Additional runs using the same command line as above shows the following message:

DEBU[0000] Found existing config. Ignoring command line opts, loading config from /var/lib/convoy  pkg=server

**Comment by yasker** [comment]
@mklatsky After initialization, "convoy daemon" would start Convoy with previous same configure, and currently you need to delete the /var/lib/convoy and tear down the convoy setup(e.g. ```dmsetup remove convoy_pool``` in order to use another setup)

What information you got when you failed to daemonize convoy for the first time?

**Comment by mklatsky** [comment]
This was on a brand new install, so there was no previous configuration.. When I ran the above command- convoy did not daemonize. It created the directory  /var/lib/convoy/, and the file /var/lib/convoy/convoy.cfg. When I stopped convoy, and removed the /var/lib/convoy/convoy.cfg file, then started it again- the file was recreated. I am unable to run convoy in a demonized mode.

**Comment by yasker** [comment]
Probably there is a little confusion here. Daemonized we said means convoy would run as an daemon/server, as docker do. It would still running in foreground as Docker do. You can either use start-stop-daemon to put it in background or start another terminal to execute command. 

As long as you see convoy start successfully, you can start issue commands through convoy CLI.

**Comment by mklatsky** [comment]
Yes- I just was updating my previous comment to that effect- I misunderstood what "daemon" did. Thank you for your quick update.
