### ISSUE TITLE
Volume stuck in purging state

### ISSUE THREAD

**Issue by kuzhao** [rancher/convoy#167]
It seems that convoy still treats the volume as it's mounted and in use after those docker services have been purged.
Detailed log from convoy storagepool container is attached below.

**Comment by kuzhao** [comment]
10/17/2016 9:55:55 AMtime="2016-10-17T01:55:55Z" level=debug msg="Processing event." event="{"id":"0dc597e6-bb90-4368-8087-9ee7431ef17d","name":"storage.volume.remove","replyTo":"reply.4719994817901404826","resourceId":"1vspm787","resourceType":"volumeStoragePoolMap","publisher":null,"transitioning":null,"transitioningMessage":null,"transitioningInternalMessage":null,"previousIds":null,"previousNames":null,"data":{"volumeStoragePoolMap":{"data":{},"created":1476169446000,"description":null,"volumeId":787,"kind":"volumeStoragePoolMap","id":787,"removed":null,"uuid":"9ed76caa-2f3d-4610-ac06-1fff1b6a3452","storagePoolId":5,"removeTime":null,"name":null,"state":"removing","type":"volumeStoragePoolMap","volume":{"data":{"fields":{"driver":"convoy-nfs"}},"created":1476169445000,"description":null,"format":null,"uri":null,"kind":"volume","id":787,"hostId":null,"instanceId":null,"zoneId":1,"accountId":7,"removed":1476412207000,"uuid":"9278f8c4-0f49-48b1-84b1-a437034adc09","deviceNumber":null,"externalId":"registry-data","imageId":null,"offeringId":null,"allocationState":"deactivating","removeTime":1476412267000,"accessMode":null,"virtualSizeMb":null,"physicalSizeMb":null,"attachedState":null,"name":"registry-data","state":"purging","type":"volume","offering":null,"instance":null,"storagePools":[{"data":{},"created":1475998130000,"description":null,"driverName":"convoy-nfs","kind":"storagePool","id":5,"agentId":16,"zoneId":1,"accountId":7,"removed":null,"uuid":"4f4f53d7-1f8e-485c-a944-f53879d867f4","externalId":"convoy-nfs","removeTime":null,"physicalTotalSizeMb":null,"external":false,"virtualTotalSizeMb":null,"volumeAccessMode":null,"name":"convoy-nfs","state":"active","type":"storagePool"}],"image":null},"storagePool":{"data":{},"created":1475998130000,"description":null,"driverName":"convoy-nfs","kind":"storagePool","id":5,"agentId":16,"zoneId":1,"accountId":7,"removed":null,"uuid":"4f4f53d7-1f8e-485c-a944-f53879d867f4","externalId":"convoy-nfs","removeTime":null,"physicalTotalSizeMb":null,"external":false,"virtualTotalSizeMb":null,"volumeAccessMode":null,"name":"convoy-nfs","state":"active","type":"storagePool"}}},"time":1476669354567,"timeoutMillis":15000,"transitioningProgress":null,"context":{"processId":"117189","logicPath":"volume.purge->(VolumePurge)->volume.deallocate->(VolumeDeallocate)->volumestoragepoolmap.remove->(VolumeStoragePoolMapRemove)","logicName":"VolumeStoragePoolMapRemove","prettyResource":"volume:787->volumeStoragePoolMap:787","processName":"volumestoragepoolmap.remove","topResourceType":"volume","resouceId":"787","resouceType":"volumeStoragePoolMap","prettyProcess":"volume.purge->volumestoragepoolmap.remove","topProcessName":"volume.purge","topResourceId":"787","processUuid":"5bb62ffe-0fc1-47ec-9fa0-4817e20131af"}}"
10/17/2016 9:55:55 AMtime="2016-10-17T01:55:55Z" level=error msg="Error processing event" err="Cannot delete volume 787. Name: registry-data. Error: Cannot delete volume registry-data. It is still mounted\n" eventId=0dc597e6-bb90-4368-8087-9ee7431ef17d eventName=storage.volume.remove resourceId=1vspm787

**Comment by nabil38** [comment]
I am having the same issue

**Comment by kuzhao** [comment]
A cleanup and relaunch of convoy stack can be workaround. But what if it's running under production env?

**Comment by mattkenn4545** [comment]
Why is this closed? Issue still remains.

**Comment by kuzhao** [comment]
@mattkenn4545 I could leave it open, but 1. as rancher is moving forward to v1.2 and there'll be a number of changes upon system architecture and 2. the issue is hard to reproduce on my side, I just closed it.
If any of you guys could come up with a stable way of reproducing I'll then reopen.
