### ISSUE TITLE
volume labels

### ISSUE THREAD

**Issue by surfr326** [rancher/convoy#174]
Docker: 1.12.2
Convoy: 0.5.0, vfs backend

Would it be possible to propagate volume labels for volumes created between hosts? Currently if I use docker volume create with convoy driver on one host and apply a label, that label does not show up on any other host with access to convoy volumes.

Thanks!

**Comment by yasker** [comment]
I don't think Docker tell label information about volume to volume drivers, so it may not possible to do it.
