### ISSUE TITLE
convoy volume lost when upgrade from convoy 0.4.3 to 0.5.0

### ISSUE THREAD

**Issue by binliuk** [rancher/convoy#175]
if i copy back the 0.4.3 version of convoy and convoy-pdata_tools, the volume is there
please anyone can help? 
But if I use the 0.4.3 version, docker 1.11.2 could not read the volume with following error:
"Error response from daemon: get jenkins_home: VolumeDriver.Get: Handler not found: POST /VolumeDriver.Get
Error: failed to start containers: 86ab
"

**Comment by binliuk** [comment]
it turns out in version 0.4.3, the config root is at /var/lib/convoy, but 0.5.0 is using /var/lib/rancher/convoy

but still when start 0.5.0 daemon with --root /var/lib/convoy, i could see all my volumes and snapshot, but the volume name is missing for all volumes, :(

**Comment by yasker** [comment]
Hi @binliuk 

We've changed the configuration format for 0.5.0, so it's not compatible with 0.4.3. The version release note warned about it...

Currently we don't support upgrade from 0.4.3 to 0.5.0, so you may want to use backup in 0.4.3 and restore in 0.5.0 to get things right.

Or it's also possible to modify the volume configuration per driver to include the information from old version, but that will require some efforts or tools to sort it out.
