### ISSUE TITLE
Managing convoy command through REST API

### ISSUE THREAD

**Issue by zepouet** [rancher/convoy#176]
Hello,

Is it possible to execute snapshot/backup/restore via REST API ?
Would you be interested by a PR about this feature ?

Thanks a lot
Best regards

**Comment by peebles** [comment]
I do not represent anyone associated with convoy, but ...

This "feature" already exists.  You can access the complete convoy REST api by sending requests to the /var/run/convoy/convoy.sock socket.  I have created a "node-convoy" project, a library you can use in NodeJS scripts for managing convoy using the API.  Even if you don't use NodeJS, you could look at the source code to see how it works.

See: https://github.com/peebles/node-convoy

**Comment by yasker** [comment]
@peebles is right, all the API already exists through the local socket.
