### ISSUE TITLE
mkdir /var/lib/rancher/convoy/convoy-*****/mnt/config: permission denied" 

### ISSUE THREAD

**Issue by SwarmKit** [rancher/convoy#180]
rancher/convoy-agent     v0.9.0 
time="2016-12-07T15:12:06Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck" 
time="2016-12-07T15:12:06Z" level=info msg="Got: driver-opts [vfs.path=/var/lib/rancher/convoy/convoy-nfs-35646f85-4ead-4ce4-a8d7-5f17809fc0dc/mnt]" 
time="2016-12-07T15:12:06Z" level=info msg="Got: ignore-docker-delete true" 
time="2016-12-07T15:12:06Z" level=info msg="Got: create-on-docker-mount true" 
time="2016-12-07T15:12:06Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-nfs-35646f85-4ead-4ce4-a8d7-5f17809fc0dc" 
time="2016-12-07T15:12:06Z" level=info msg="Got: drivers [vfs]" 
time="2016-12-07T15:12:06Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/convoy-convoy-nfs.sock daemon --driver-opts=vfs.path=/var/lib/rancher/convoy/convoy-nfs-35646f85-4ead-4ce4-a8d7-5f17809fc0dc/mnt --ignore-docker-delete=true --create-on-docker-mount=true --root=/var/lib/rancher/convoy/convoy-nfs-35646f85-4ead-4ce4-a8d7-5f17809fc0dc --drivers=vfs]" 
time="2016-12-07T15:12:06Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-nfs-35646f85-4ead-4ce4-a8d7-5f17809fc0dc" pkg=daemon 
time="2016-12-07T15:12:06Z" level=debug msg= driver=vfs driver_opts=map[vfs.path:/var/lib/rancher/convoy/convoy-nfs-35646f85-4ead-4ce4-a8d7-5f17809fc0dc/mnt] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-nfs-35646f85-4ead-4ce4-a8d7-5f17809fc0dc" 
time="2016-12-07T15:12:06Z" level=debug msg="Cleaning up environment..." pkg=daemon 
time="2016-12-07T15:12:06Z" level=error msg="mkdir /var/lib/rancher/convoy/convoy-nfs-35646f85-4ead-4ce4-a8d7-5f17809fc0dc/mnt/config: permission denied" 
{
	"Error": "mkdir /var/lib/rancher/convoy/convoy-nfs-35646f85-4ead-4ce4-a8d7-5f17809fc0dc/mnt/config: permission denied"
}
time="2016-12-07T15:12:06Z" level=info msg="convoy exited with error: exit status 1" 
time="2016-12-07T15:12:06Z" level=info msg=Exiting. 
Waiting for metadata

**Comment by yasker** [comment]
Please use `rancher-nfs` in Rancher now.

**Comment by jgato** [comment]
The same issue here. It seems that rancher-nfs is only available in rancher 1.2 but we are using 1.1. I would like not to update the version...
