### ISSUE TITLE
Backup URL is wrong for Device Mapper storage backup

### ISSUE THREAD

**Issue by rootsongjc** [rancher/convoy#182]
I start the convoy deamon with devicemapper driver. When I backup the snap1vol1 with `convoy backup create snap1vol1 --dest vfs:///opt/convoy/` I got an URL vfs:///opt/convoy/?backup=backup-da14db80509a402b\u0026volume=vol1
I think the URL a wrong because it's no host identifying.
I can't restore the snapshot on other node.
**environment**
convoy 0.5
docker 1.11.1
centos 7.2.1511
docker storage driver: overlay

**Comment by yasker** [comment]
The backup URL is right and it expects the NFS to be mounted at the same location on the host( `/opt/convoy`). Convoy itself doesn't know about NFS server currently, only local path.
