### ISSUE TITLE
Convoy Daemon is not starting

### ISSUE THREAD

**Issue by sheridavandenbent** [rancher/convoy#184]
Hi,

I'm trying to get a Convoy Daemon running following the quickstart instructions mentioned in the readme. However, when I run the following line:

`sudo convoy daemon --drivers devicemapper --driver-opts dm.datadev=/dev/loop5 --driver-opts dm.metadatadev=/dev/loop6`

It runs up to a certain point, and then freezes. This is the result:

`
DEBU[0000] Found existing config. Ignoring command line opts, loading config from /var/lib/rancher/convoy  pkg=daemon
DEBU[0000]                                               driver=devicemapper driver_opts=map[dm.datadev:/dev/loop5 dm.metadatadev:/dev/loop6] event=init pkg=daemon reason=prepare root=/var/lib/rancher/convoy
DEBU[0000] Found created pool, skip pool reinit          pkg=devmapper
DEBU[0000]                                               driver=devicemapper event=init pkg=daemon reason=complete
DEBU[0000] Registering GET, /snapshots/                  pkg=daemon
DEBU[0000] Registering GET, /backups/list                pkg=daemon
DEBU[0000] Registering GET, /backups/inspect             pkg=daemon
DEBU[0000] Registering GET, /info                        pkg=daemon
DEBU[0000] Registering GET, /volumes/list                pkg=daemon
DEBU[0000] Registering GET, /volumes/                    pkg=daemon
DEBU[0000] Registering POST, /volumes/create             pkg=daemon
DEBU[0000] Registering POST, /volumes/mount              pkg=daemon
DEBU[0000] Registering POST, /volumes/umount             pkg=daemon
DEBU[0000] Registering POST, /snapshots/create           pkg=daemon
DEBU[0000] Registering POST, /backups/create             pkg=daemon
DEBU[0000] Registering DELETE, /snapshots/               pkg=daemon
DEBU[0000] Registering DELETE, /backups                  pkg=daemon
DEBU[0000] Registering DELETE, /volumes/                 pkg=daemon
DEBU[0000] Registering plugin handler POST, /VolumeDriver.List  pkg=daemon
DEBU[0000] Registering plugin handler POST, /Plugin.Activate  pkg=daemon
DEBU[0000] Registering plugin handler POST, /VolumeDriver.Create  pkg=daemon
DEBU[0000] Registering plugin handler POST, /VolumeDriver.Remove  pkg=daemon
DEBU[0000] Registering plugin handler POST, /VolumeDriver.Mount  pkg=daemon
DEBU[0000] Registering plugin handler POST, /VolumeDriver.Unmount  pkg=daemon
DEBU[0000] Registering plugin handler POST, /VolumeDriver.Path  pkg=daemon
DEBU[0000] Registering plugin handler POST, /VolumeDriver.Get  pkg=daemon
`

When I exit, the following error is shown:

`Caught signal interrupt: shutting down.
DEBU[0235] Cleaning up environment...                    pkg=daemon
ERRO[0235] http server erroraccept unix /var/run/convoy/convoy.sock: use of closed network connection  pkg=daemon`

Am I doing something wrong? Is there a bug somewhere? I'm fairly new with docker and rancher, so any help would be really appreciated :)

**Comment by yasker** [comment]
It's daemon... You need to run `convoy` or `docker` cmdline to use the service it provides.
