### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by jhmnieuwenhuis** [rancher/convoy#210]
Hi,
when using nfs volumes and restoring a backup I get a timeout error.
I use the --cmd-timeout=10m 
But after about 1 minuut the create commands exits 

convoy create d4d-hans-volume --backup vfs:///mnt/nfs1/backup?backup=backup-53065b720c5f4c72\u0026volume=d4d-dbs-volume
ERRO[0072] Error response from server, Timeout executing: tar [xf /mnt/nfs1/d4d-hans-volume/backup-53065b720c5f4c72.bak -C /mnt/nfs1/d4d-hans-volume.tmp], output , error <nil>
 
{
	"Error": "Error response from server, Timeout executing: tar [xf /mnt/nfs1/d4d-hans-volume/backup-53065b720c5f4c72.bak -C /mnt/nfs1/d4d-hans-volume.tmp], output , error \u003cnil\u003e\n"
}

# convoy --version
convoy version v0.5.0

**Comment by yasker** [comment]
Hi @jhmnieuwenhuis 

It's a bug in backup area, the timeout should be much longer for tar command.

We will fix that.

**Comment by jhmnieuwenhuis** [comment]
Ok, Thanks for the quick response !

Any idea when this can be expected.
I may need to look for another solution to back/restore in the mean time...

Regards,

Hans

**Comment by yasker** [comment]
Probably a week or two, current we're busy on another project.

**Comment by yasker** [comment]
hi @jhmnieuwenhuis 

Can you check what's the `CmdTimeout` in your `/var/lib/rancher/convoy`? I think the timeout wasn't updated in this case.

**Comment by jhmnieuwenhuis** [comment]
You are right !

I added the CmdTimeout to my servicefile, but it was not updated in the /var/lib/rancher/convoy/convoy.cfg

After adding it to the convoy.cfg file it worked as expected.

I am on Centos 7 

Regards,

Hans Nieuwenhuis

**Comment by yasker** [comment]
Glad it work!
