### ISSUE TITLE
Works with Rancher?

### ISSUE THREAD

**Issue by peebles** [rancher/convoy#217]
I am starting to play with the Rancher UX.  I do not see this storage driver in any of the catalogs.  Is there a private catalog somewhere where this driver is present?

The "rancher-ebs" driver seems to be something different.

**Comment by nicodmf** [comment]
Idem

**Comment by yasker** [comment]
Convoy is stand alone storage plugin only works with Docker.

Rancher is using Rancher Storage https://github.com/rancher/storage
