### ISSUE TITLE
How to uninstall convoy

### ISSUE THREAD

**Issue by jhmnieuwenhuis** [rancher/convoy#218]
Hi,
I want to uninstall convoy.
I disabled and stopped the convoy service and the docker service.
I removed the spec file :  /etc/docker/plugins/convoy.spec

But when I try to start docker again i get an error 
level=warning msg="Unable to locate plugin: convoy .."

And docker does not start......

What am I doing wrong ?

Centos 7
Docker 17.07.0-ce
convoy v0.5.0

**Comment by yasker** [comment]
Seems you still have volume with driver convoy, so Docker will try to find them.

See 'docker volume ls'.

**Comment by jhmnieuwenhuis** [comment]
Hello,
I deleted all convoy volumes.
But still when I stop convoy service, docker will not start.

[root@csdevel rancher]# docker volume ls
DRIVER              VOLUME NAME
local               dev_dev-html-volume
local               dev_dev-mailhog-volume
local               dev_dev-psql-volume
local               dev_drupal-backup-volume
[root@csdevel rancher]# convoy list
{}
