### ISSUE TITLE
Docker will not start when i stop convoy

### ISSUE THREAD

**Issue by jhmnieuwenhuis** [rancher/convoy#219]
Hi,
I want to uninstall convoy.
I disabled and stopped the convoy service and the docker service.
I removed the spec file :  /etc/docker/plugins/convoy.spec

But when I try to start docker again i get an error 
level=warning msg="Unable to locate plugin: convoy .."

I deleted all convoy volumes

[root@csdevel rancher]# docker volume ls
DRIVER              VOLUME NAME
local               dev_dev-html-volume
local               dev_dev-mailhog-volume
local               dev_dev-psql-volume
local               dev_drupal-backup-volume
[root@csdevel rancher]# convoy list
{}

What am I doing wrong ?
Centos 7
Docker 17.07.0-ce
convoy v0.5.0
#

**Comment by jhmnieuwenhuis** [comment]
Extra Info
========
If I stop convoy and try to restart docker, I see the following error :+1: 
[root@csdevel ~]# systemctl status docker -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: activating (start) since Sat 2017-09-16 20:14:26 CEST; 2min 29s ago
     Docs: https://docs.docker.com
 Main PID: 8445 (dockerd)
   Memory: 15.2M
   CGroup: /system.slice/docker.service
           ├─8445 /usr/bin/dockerd
           └─8453 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc

Sep 16 20:16:27 csdevel.jhmnlocal dockerd[8445]: time="2017-09-16T20:16:27.417107034+02:00" level=warning msg="Error restoring volume" driver=convoy error="error while checking if volume \"\" exists in driver \"convoy\": Error looking up volume plugin convoy: legacy plugin: Post http://%2Fvar%2Frun%2Fconvoy%2Fconvoy.sock/Plugin.Activate: dial unix /var/run/convoy/convoy.sock: connect: connection refused" volume=
Sep 16 20:16:27 csdevel.jhmnlocal dockerd[8445]: time="2017-09-16T20:16:27.418061827+02:00" level=warning msg="Unable to connect to plugin: /var/run/convoy/convoy.sock/Plugin.Activate: Post http://%2Fvar%2Frun%2Fconvoy%2Fconvoy.sock/Plugin.Activate: dial unix /var/run/convoy/convoy.sock: connect: connection refused, retrying in 1s"
Sep 16 20:16:28 csdevel.jhmnlocal dockerd[8445]: time="2017-09-16T20:16:28.418879794+02:00" level=warning msg="Unable to connect to plugin: /var/run/convoy/convoy.sock/Plugin.Activate: Post http://%2Fvar%2Frun%2Fconvoy%2Fconvoy.sock/Plugin.Activate: dial unix /var/run/convoy/convoy.sock: connect: connection refused, retrying in 2s"
Sep 16 20:16:30 csdevel.jhmnlocal dockerd[8445]: time="2017-09-16T20:16:30.419769834+02:00" level=warning msg="Unable to connect to plugin: /var/run/convoy/convoy.sock/Plugin.Activate: Post http://%2Fvar%2Frun%2Fconvoy%2Fconvoy.sock/Plugin.Activate: dial unix /var/run/convoy/convoy.sock: connect: connection refused, retrying in 4s"
Sep 16 20:16:34 csdevel.jhmnlocal dockerd[8445]: time="2017-09-16T20:16:34.421621857+02:00" level=warning msg="Unable to connect to plugin: /var/run/convoy/convoy.sock/Plugin.Activate: Post http://%2Fvar%2Frun%2Fconvoy%2Fconvoy.sock/Plugin.Activate: dial unix /var/run/convoy/convoy.sock: connect: connection refused, retrying in 8s"

But docker volume ls shows no convoy volumes and convoy list is empty :

[root@csdevel ~]# docker volume ls
DRIVER              VOLUME NAME
local               dev_dev-html-volume
local               dev_dev-mailhog-volume
local               dev_dev-psql-volume
local               dev_drupal-backup-volume
[root@csdevel ~]# convoy list
{}

**Comment by jhmnieuwenhuis** [comment]
Solution
Finaly found a solution 
# cd /var/lib/docker/volumes
# rm metadata.db
# systemctl restart docker

So it seems the metadata.db was somehow corrupt....

Regards

**Comment by yasker** [comment]
Thanks for figuring it out!
