### ISSUE TITLE
backup create with vfs has case-sensitivity issues

### ISSUE THREAD

**Issue by prelegalwonder** [rancher/convoy#22]
When using convoy v0.3 to create a backup of a snapshot with a vfs destination, it appears that convoy does some sort of toLower() function on the path name causing an invalid path to be attempted. 

**Example:**
```
~# convoy backup create jenkins-initial-snapshot --dest vfs:///mnt/nfs/mynfsserver/Backup/docker/convoy
ERRO[0000] Error response from server, VFS path /mnt/nfs/mynfsserver/backup/docker/convoy doesn't exist or is not a directory

{
        "Error": "Error response from server, VFS path /mnt/nfs/mynfsserver/backup/docker/convoy doesn't exist or is not a directory\n"
}
~#
```
Notice in the vfs path I provide, Backup is uppercase, and when convoy returns it back, it's lowercase. I believe this is the reason it's not finding the vfs target.

**Comment by yasker** [comment]
I am looking into this.

**Comment by yasker** [comment]
Hi @prelegalwonder 

Could you try the binary below to see if it solves your issue? Only replace "convoy" binary from tarball is fine.

https://s3-us-west-1.amazonaws.com/sheng/convoy.tar.gz

**Comment by prelegalwonder** [comment]
@yasker Thank you! Confirmed, I was able to use the directory with the upper-case name.

**Comment by yasker** [comment]
Thanks @prelegalwonder , I would push the fix and include it in the next release. In the meantime you can still using the binary, it's based off master and should be stable.
