### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by wildone** [rancher/convoy#220]
Would be good to know if we need to seek alternatives :)

**Comment by fentas** [comment]
This fork is (more or less) in development.
https://github.com/medallia/convoy

Do you mind to share alternatives for convoy, if you have any?

**Comment by mahnunchik** [comment]
Any news?

**Comment by yasker** [comment]
The project is currently in the maintenance mode, we are no longer actively develop it. We will only focus on critical bug fixes. 

Of course, PR are always welcome.

**Comment by mahnunchik** [comment]
Hi @yasker do you know good alternatives?

**Comment by mgagliardo** [comment]
I know it's not exactly the same but you might want to look into [OpenEBS](https://github.com/openebs) (Have not tried it yet though)

**Comment by yasker** [comment]
@mgaliardo OpenEBS is not exactly what Convoy is. I can think of EMC Rex-ray as an alternative. Also, if you're interested in OpenEBS, they're built on top of Rancher Longhorn. We're actively developing Longhorn.

**Comment by llazzaro** [comment]
I'm here to say "hello!"

**Comment by unglaublicherdude** [comment]
Has anyone found a solution? Does anyone already use the fork https://github.com/medallia/convoy?
