### ISSUE TITLE
ERRO[0100] http server erroraccept unix /var/run/convoy/convoy.sock: use of closed network connection  pkg=daemon

### ISSUE THREAD

**Issue by michaellacastro** [rancher/convoy#222]
**Information:**
VM OS: Centos 7
docker  --version: Docker version 17.09.0-ce, build afdb6d4

-----

**Problem**

Hello, I have recently tried to install Convoy and followed the quick start guide and when I execute the sudo command to start the daemon for the COnvoy plugin
`sudo convoy daemon --drivers devicemapper --driver-opts dm.datadev=/dev/loop5 --driver-opts dm.metadatadev=/dev/loop6`

it returns this output
![screen shot 2017-11-20 at 9 28 04 am](https://user-images.githubusercontent.com/31716728/32998323-2779611c-cdd5-11e7-9ce8-8733f34f5ef0.png)

and when I cancel it outputs:
![screen shot 2017-11-20 at 9 28 32 am](https://user-images.githubusercontent.com/31716728/32998330-34c7c6f6-cdd5-11e7-999f-955339f77d28.png)

---

**Points:**
1. I tried even shutting of my firewall with the VM, nope.

2. Checked the .sock file
![screen shot 2017-11-20 at 9 28 51 am](https://user-images.githubusercontent.com/31716728/32998346-43f8dbba-cdd5-11e7-857e-c06ac59973dc.png)

3. Checked the directory 
![screen shot 2017-11-20 at 9 29 26 am](https://user-images.githubusercontent.com/31716728/32998354-567f70d2-cdd5-11e7-9f87-6ac821170f1f.png)

--

**Question:**
What could I be missing? Am I doing something wrong? I have tried it on 2 other VMs and its still not working and I dont know what it means please help :<. Thank you!

_Blessings_

**Comment by yasker** [comment]
Convoy daemon is running as a daemon, so it will continue running until you stop it.

You can run Convoy daemon in one console or start it as a service, then use Convoy (cli) to connect to it. Or create Docker volume with it.

**Comment by michaellacastro** [comment]
Wait isnt running this command : "sudo convoy daemon --drivers devicemapper --driver-opts dm.datadev=/dev/loop5 --driver-opts dm.metadatadev=/dev/loop6" supposed to start it? My problem is that I cant start it. I get stuck in this step and I dont know whats wrong

**Comment by michaellacastro** [comment]
![screen shot 2017-11-21 at 9 08 47 am](https://user-images.githubusercontent.com/31716728/33049582-c978ab1e-ce9b-11e7-9136-09b91666c208.png)

cause if i run it in a window and try a convoy command in another window it appears like this

**Comment by michaellacastro** [comment]
@yasker

**Comment by Gapmeister66** [comment]
I'm late to the party but I think that yasker means you should run the daemon in the background somehow:

e.g 
`convoy daemon --drivers devicemapper --driver-opts dm.datadev=/dev/loop5 --driver-opts dm.metadatadev=/dev/loop6 &`

When it hangs it is actually still running correctly, so killing it is not what you want to do :)
Once I realised this I was able to continue to:

`docker` run -v vol1:/vol1 --volume-driver=convoy alpine touch /vol1/foo

Instructions at:  https://github.com/rancher/convoy
