### ISSUE TITLE
Does VFS mode support any filesystem?

### ISSUE THREAD

**Issue by ewerk-pnahratow** [rancher/convoy#223]
This is a question not an issue.

Since the call for using NFS doesn't care about the NFS server but the already mounted directory.

```bash
sudo convoy daemon --drivers vfs --driver-opts vfs.path=<vfs_path>
```

Does that mean I could use anything as long as it is a valid directory? I'm thinking about backing my persistence layer using [OCFS2](https://en.wikipedia.org/wiki/OCFS2) and convoy but I'm not sure if I understand the meaning of *VFS* correctly.

**Comment by yasker** [comment]
Yes, it supports any mounted directories on the host.
