### ISSUE TITLE
Ability to search backups by destination

### ISSUE THREAD

**Issue by djenriquez** [rancher/convoy#32]
Is there a way to search backups at a given location? We are currently creating snapshots and backing them up to S3 using a cron job. The script that cron runs uses titles the snapshot `${SERVICE}_${INSTANCE_ID}_${TIMESTAMP}`. When looking to restore from a backup, its really difficult to recreate this name because the timestamp is formatted `TIMESTAMP=$(date +%Y%m%d%H%M%S)` and the instance ID is some arbitrary ID created by AWS.

Ideally, we would want to point to our S3 backend and be given a list of backups to restore from. Is this a feature that exists today?

**Comment by yasker** [comment]
Hi @djenriquez,

We don't support list with EBS driver, but for VFS and Device Mapper, you can use "convoy backup list <url>" for list all the backups, though, it may take quite a while. See [here](https://github.com/rancher/convoy/blob/master/docs/cli_reference.md#list-1) for details.

**Comment by djenriquez** [comment]
Thank you @yasker, this is exactly what I was looking for!
