### ISSUE TITLE
inconsistent behaviour on container removal

### ISSUE THREAD

**Issue by jaroslavl1** [rancher/convoy#36]
There are 2 ways how a container can be removed:
* automatic removal on exit when --rm=true is used - leads to unmount & delete of volume
* manual removal after "docker ps -a" followed by "docker rm {containerId}" of some inactive container - doesn't lead to volume deletion. Volume is already unmounted since container is inactive.

In the 1st case deletion will occur also in case the volume was created by convoy create via command line. If volume is created via command line I think it should not be automatically deleted. It should probably be symmetric - if created automatically, can be deleted automatically. If created manually, must be deleted manually.

This problem was detected with vfs driver, most likely affects all drivers.

**Comment by yasker** [comment]
We define behavior in this way so that user won't accidentally delete useful data. The named volume created by docker is still valid volume to be reused.

Anytime user want to delete the volume it can be done through Convoy.

Marked as "Won't fix"
