### ISSUE TITLE
Create not existing volume during docker run?

### ISSUE THREAD

**Issue by pwFoo** [rancher/convoy#41]
At the moment the volume have to be created before "docker run" command?
Should a not existing volume automatically created during docker run?

**Comment by yasker** [comment]
@pwFoo In fact you can just use "docker run" to create the volume. Everything would be set to default value in that case, and volume would be created with the specified volume name. It's supported from day one. If you have any issue with it please report a bug. :smile:

**Comment by pwFoo** [comment]
I tried to create new volumes via rancher-compose, but container creation / start failed.
Created volumes manually first, re-run rancher-compose and all works fine.

I'll do some more tests ;)

**Comment by pwFoo** [comment]
I think it should work fine... Tested with a docker-compose files
