### ISSUE TITLE
AvailablityZone spelling?

### ISSUE THREAD

**Issue by jlai** [rancher/convoy#45]
"AvailablityZone" (missing i) appears to be a typo unless there's some compatibility reason for keeping it that way. Referenced in both [ebs.md](https://github.com/rancher/convoy/blob/8dd4ac07e5a0c88fe4d3a725f964ed280c520462/docs/ebs.md) and [ebs.go](https://github.com/rancher/convoy/blob/64cf1db26f40eca8d83e0ca7cb811e1f08b42749/ebs/ebs.go)

**Comment by yasker** [comment]
Thanks, would fix soon. :)
