### ISSUE TITLE
Support for s3-compatible backends that aren't on amazon

### ISSUE THREAD

**Issue by nnordrum** [rancher/convoy#46]
I can get to it with the awscli, and it's using the same underlying api, so it shouldn't be that difficult.

Here's what I do in awscli:
`aws --endpoint-url https://some.url.that.hosted.internally/ s3 ls`

**Comment by pimpim** [comment]
+1

**Comment by avoinea** [comment]
+1

**Comment by demarant** [comment]
+1 we need this

**Comment by PatrickHuetter** [comment]
+1

**Comment by giovannicandido** [comment]
I create a image that use rclone to sync to different backends including custom S3: https://github.com/atende/infra-volume-backup

Rclone: http://rclone.org/

It basically mount the volume in the container and sync its contents.

Would be nice to have such integration in convoy.

**Comment by yasker** [comment]
Supported added by #228
