### ISSUE TITLE
AWS creds not loading from ENV or ~/.aws/credentials

### ISSUE THREAD

**Issue by colebrumley** [rancher/convoy#57]
I've got a fresh AWS instance with Docker 1.9.1 and Convoy v0.4.1 that refuses to load AWS credentials for S3. I started with setting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, then tried setting those in root's environment, then tried creating `~/.aws/credentials` for my user and then for root too, all with no luck. No matter what I've tried, Convoy keeps telling me:
```
ERRO[0000] Error response from server, AWS Error:  NoCredentialProviders no valid providers in chain <nil>

{
	"Error": "Error response from server, AWS Error:  NoCredentialProviders no valid providers in chain \u003cnil\u003e\n\n"
}
```
For what it's worth, I installed the `awscli` package to make sure that it wasn't a credential typo or something and it can connect just fine:
```
$ aws s3 ls
2015-09-22 21:35:55 env-backup
2015-12-14 19:05:07 repo-s3-logs
2015-09-17 04:27:53 repo
2015-12-21 20:59:51 repo-io
```
Not sure what's different about this environment versus your test environment, have you seen this before?

**Comment by mklatsky** [comment]
I am running into exactly the same issue.

**Comment by yasker** [comment]
@colebrumley @mklatsky 

I haven't seen this issue before, and mostly Convoy credentials should work as far as `awscli` works. Convoy is using [aws-go-sdk](https://github.com/aws/aws-sdk-go) to handle all aws relate works.

Convoy is running as `sudo` user in your case? You should able to use these lines in `visudo` to keep environment variables:

```
Defaults env_keep+="AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY"
```

Also you can check if root environment's `awscli` runs well, by using root user(if you haven't done so)

**Comment by mklatsky** [comment]
@yasker I could have sworn I tested that my environment kept the appropriate credentials, but as of this morning (and with a fresh mind) I was able to deploy a set of containers, and the EBS volume was correctly created and mounted as expected. 
I will update if any other issues related to this present themselves, but at this point it looks like the issue was on my side.

Thank you for your response.

**Comment by colebrumley** [comment]
Hmm, I'm still not getting any creds. To be sure, I went through a from-scratch reconstruction using `docker-machine`:

```bash
docker-machine create -d digitalocean convoy-s3-test
docker-machine ssh convoy-s3-test
```
(logged in as root)

```bash
wget https://github.com/rancher/convoy/releases/download/v0.4.1/convoy.tar.gz
tar xzvf convoy.tar.gz
mv convoy/convoy* /usr/local/bin/
mkdir -p /etc/docker/plugins/
echo "unix:///var/run/convoy/convoy.sock" > /etc/docker/plugins/convoy.spec
convoy daemon --drivers vfs --driver-opts vfs.path=/var/lib/convoy/volumes
```
(new shell)
```bash
apt-get install -y awscli
export AWS_SECRET_ACCESS_KEY=<key>
export AWS_ACCESS_KEY_ID=<key>
aws s3 ls
 -> <my expected buckets>
convoy create test
convoy snapshot create test
 -> 27009316-2268-4b76-b263-07a5a80a15fe
convoy backup create --dest s3://my-bucket@us-east-1/ops/ 27009316-2268-4b76-b263-07a5a80a15fe
 -> ERRO[0000] Error response from server, AWS Error:  NoCredentialProviders no valid providers in chain <nil>
aws s3 ls s3://my-bucket/ops/
 -> <bucket contents as expected>
```

I can reproduce this at will using the above. It's all done as root and the AWS client works fine as far as I can tell.

**Comment by yasker** [comment]
Hi @colebrumley 

I just reproduce the issue with @deniseschannon 's help. Then I found if I using the credential file `~/.aws/credentials` it would works... If that can workaround the issue for you please let me know. It appear to be `aws-go-sdk` bug. I would investigate more.

**Comment by mklatsky** [comment]
Oddly, this problem has cropped up again after I tore down and recreated my previous environment, (2 machines in the swarm, 1 swarm master).

I am exhibiting exactly the same behavior as @colebrumley. The behavior exists even though I can see the AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID in my environment and aws s3 ls displays the expected buckets.

IF I create the ~/.aws/credentials file with the following:

[default]
aws_access_key_id = KEY
aws_secret_access_key = SECRET_KEY

then I can create volumes, etc. It seems that population from envvars either does not work, or is not reliable for some reason. 

The file also needs to be created on each machine in the swarm cluster. My local credentials (from where I run my docker-compose commands) do not seem to come into play.

**Comment by colebrumley** [comment]
Very strange. Using the method from my previous comment I switched the `export` steps to: 

```bash
mkdir -p ~/.aws; echo -e "[default]\naws_access_key_id = <key>\naws_secret_access_key = <secret key>\n" > ~/.aws/credentials
```
And I was able to create a backup.  I could have sworn I tried this before when I was preparing to open the issue...

Actually, now that I'm thinking back on it I was starting convoy using an init script that must not be doing something right because I still can't create backups on that box, so that's probably me and not convoy (it's using the `start-stop-daemon` and running as a non-root user, so there are definitely more places to mess up).

Thanks for the help! Env variables are preferable for me over the `~/.aws/credentials` file, but at least there's a workaround :+1:. Hopefully whenever you get around to updating the AWS SDK version in convoy it'll work itself out.  Feel free to close this issue at your leisure.

**Comment by yasker** [comment]
Verified it's no longer an issue on 0.4.2.

Also environment variables need to be set before start convoy daemon, otherwise they won't work.

**Comment by jonathan-kosgei** [comment]
Hi I'm running into this too, but oddly I can't print out my convoy version

```
root@ip-172-31-23-121:~# convoy version
ERRO[0000] Unrecognized command: version                
{
	"Error": "Unrecognized command: version"
}
```

```
root@ip-172-31-23-121:~# convoy list
{}
root@ip-172-31-23-121:~# convoy create test_volume
ERRO[0000] Error response from server, AWS Error:  NoCredentialProviders no valid providers in chain <nil>

 
{
	"Error": "Error response from server, AWS Error:  NoCredentialProviders no valid providers in chain \u003cnil\u003e\n\n"
}
```

My systemd file looks like this

```
[Unit]
Description=Convoy volumes
Requires=docker.service
After=docker.service

[Service]
EnvironmentFile=-/root/.aws/credentials
EnvironmentFile=-/root/.aws/config
ExecStart=/usr/local/bin/convoy daemon --drivers ebs 2>> /var/log/convoy/stderr.log 1>> /var/log/convoy/stdout.log
ExecStop=killall convoy
Environment=HOME=/root
Restart=always

[Install]
WantedBy=local.target
```

**Comment by jonathan-kosgei** [comment]
This is not an issue on 0.4.2 but it is on 0.5.0
