### ISSUE TITLE
Creating volume from snapshot

### ISSUE THREAD

**Issue by mkuchin** [rancher/convoy#62]
Is any way to create volume from snapshot directly or rollback volume to some past snapshot?
I couldn't find anything about such operations in documentation.

**Comment by yasker** [comment]
Hi @mkuchin 

There is no rollback from snapshot feature so far. Currently you need to restore from a backup to create a new volume.

If we implement rollback in the future, volume needs to be umounted at the point as well.

**Comment by injectives** [comment]
I was also looking for this. It can be very useful for development, for instance make a quick snapshot before trying to change something and have opportunity to rollback.
Is it possible to create local backup storage as a workaround?

**Comment by injectives** [comment]
Found. --dest vfs:///opt/backup/ has helped.

**Comment by dgafka** [comment]
Is this feature being implemented? 

Sorry, for responding on closed issue, but I didn't want to create exactly the same new one.

**Comment by yasker** [comment]
Hi @dgafka 

We haven't implemented the feature yet...
