### ISSUE TITLE
Timeout when creating new volume

### ISSUE THREAD

**Issue by mwilmes** [rancher/convoy#73]
In v0.4.3 there is now a timeout for calls implemented. However on systems with somewhat slow disk subsystem I get timeouts:

`$ sudo docker volume create --name test --driver=convoy
Error response from daemon: create test: Timeout executing: mkfs [-t ext4 /dev/mapper/4d781f9e-a7ee-42b9-9e70-fb04c6ccd5ea], output , error <nil>`

Is the timeout configurable or should it even not be in effect during creation calls?

**Comment by yasker** [comment]
Time out is 1 minute for each command, it's used to prevent Convoy stuck on one volume, we thought it's more than enough...

It's hard for it to be customizable for now, is there a reason that mkfs would take more than one minute? The disk is too big?

**Comment by binghamchris** [comment]
FYI I've run into the same problem with snapshot creation. Logged that here as issue https://github.com/rancher/convoy/issues/99 with details of how I cam to run into the 60 second limit and some initial ideas for enhancements. Hope this is helpful :)

**Comment by yasker** [comment]
We have timeout thanks to @jinuxstyle , at https://github.com/rancher/convoy/commit/6a0a116d3aa4c8fdfe54f447be5e111cf0889bc5
