### ISSUE TITLE
Agent restart causes attached volumes to lose connection

### ISSUE THREAD

**Issue by haswalt** [rancher/convoy#74]
I have a couple of containers connected to GlusterFS using the convoy agent / plugin. Sometimes the convoy agent restarts (I'm not sure why as no longs currently). It comes back up straight away but unless I reboot the containers with mounted volumes they lose their volumes.

This means that randomly (happens every couple of days) I lose all data in my containers and they have to be restarted.

It seems that convoy is resilient to restarts of the agent and I can therefore assume it isn't resilient to network failure either.

**Comment by yasker** [comment]
Convoy agent shouldn't restart by itself, do you have any log around to show why it's happened?

Sounds like when Convoy restart it remount the volume. I would check on that part.

**Comment by haswalt** [comment]
I'll see if I can get some logs. Currently running from the catalog so no debut switch but I'll set up a custom stack.

Harry Walter

M: +44 (0)784 9503 950<tel:+44%20784%209503%20950>
W: harrywalter.co.uk<http://harrywalter.co.uk/>
