### ISSUE TITLE
Handler not found: POST /VolumeDriver.List  

### ISSUE THREAD

**Issue by yoanisgil** [rancher/convoy#87]
I'm running convoy like this a `convoy daemon --debug --drivers ebs`, however I get this error:

```
DEBU[0000] Registering plugin handler POST, /VolumeDriver.Path  pkg=daemon
DEBU[0000] Handle plugin activate: POST /Plugin.Activate  pkg=daemon
DEBU[0000] Response:  {
	"Implements": [
		"VolumeDriver"
	]
}  pkg=daemon
ERRO[0000] Handler not found: POST /VolumeDriver.List    pkg=daemon
```

Docker version is:

```
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64
```

and Convoy version is:

```
convoy --version
convoy version 0.4.3
```

Any ideas what might be going on?

**Comment by yoanisgil** [comment]
Just downloaded this release:

https://github.com/rancher/convoy/releases/download/v0.5.0.2-rancher/convoy.tar.gz

and I'm no longer experiencing this issue.

**Comment by yasker** [comment]
The new `List` and `Get` API would be supported by upcoming v0.5 Convoy release. The `-rancher` version doesn't contain backward compatibility fix for backup restore of previous version. I would release officially v0.5 Convoy after we fix that.

**Comment by yasker** [comment]
Should be supported by https://github.com/rancher/convoy/releases/tag/v0.5.0-rc1
