### ISSUE TITLE
starting with manual created devices fails

### ISSUE THREAD

**Issue by jhmnieuwenhuis** [rancher/convoy#90]
Hi,

I want to use convoy on disk witch already has partions on it.
I am on Centos 7

I created two new partitions : ( /dev/sda3 100G and /dev/sda4 500M ) 

/dev/sda3       236980224   446695423   104857600   83  Linux
/dev/sda4       446695424   447719423         512000   83  Linux

If I run convoy daemon  --drivers devicemapper  --driver-opts dm.datadev=/dev/sda3  --driver-opts dm.metadatadev=/dev/sda4

I get errors :

DEBU[0000] Creating config at /var/lib/convoy            pkg=daemon
DEBU[0000]                                               driver=devicemapper driver_opts=map[dm.datadev:/dev/sda3 dm.metadatadev:/dev/sda4] event=init pkg=daemon reason=prepare root=/var/lib/convoy
DEBU[0000] libdevmapper(7): ioctl/libdm-iface.c:1750 (4) dm version   OF   [16384] (*1) 
DEBU[0000] libdevmapper(7): ioctl/libdm-iface.c:1750 (4) dm create convoy-pool  OF   [16384] (*1) 
DEBU[0000] libdevmapper(7): ioctl/libdm-iface.c:1750 (4) dm reload convoy-pool  OF   [16384] (*1) 
ERRO[0000] libdevmapper(3): ioctl/libdm-iface.c:1768 (-1) device-mapper: reload ioctl on convoy-pool failed: Invalid or incomplete multibyte or wide character 
DEBU[0000] libdevmapper(7): ioctl/libdm-iface.c:1359 (0) <backtrace> 
DEBU[0000] libdevmapper(7): ioctl/libdm-iface.c:1750 (4) dm remove convoy-pool  OF   [16384] (*1) 
DEBU[0000] libdevmapper(7): libdm-common.c:1351 (4) convoy-pool: Stacking NODE_DEL [verify_udev] 
DEBU[0000] libdevmapper(7): libdm-common.c:1351 (4) convoy-pool: Processing NODE_DEL [verify_udev] 
DEBU[0000] Cleaning up environment...                    pkg=daemon
ERRO[0000] Error running DeviceCreate (CreatePool) dm_task_run failed 
{
	"Error": "Error running DeviceCreate (CreatePool) dm_task_run failed"
}

What can be the issue ???

**Comment by jhmnieuwenhuis** [comment]
Hi, 
Solved it.
It seems that although I created new partitions they where not empty.

Id did 
dd if=/dev/zero of=/dev/sda3
dd if=/dev/zero of=/dev/sda4

and then issued the command again and it worked !!

**Comment by yasker** [comment]
Glad you found the problem!

**Comment by sebihiy** [comment]
in my case i would like to use : 
$ sudo dd if=/dev/zero of=/dev/loop5 
$ sudo dd if=/dev/zero of=/dev/loop6
is it possible to use that ?
