### ISSUE TITLE
How can I check mountpoint via mountinfo

### ISSUE THREAD

**Issue by jay-lau** [rancher/convoy#92]
Hi, I have some test with convoy and nfs, the steps are as following:

```
root@mesos002:~# convoy list
{}
root@mesos002:~# convoy create dvd1
f210b3a2-bf40-4d5c-bd74-9e8b6666bb9a
root@mesos002:~# convoy mount dvd1
/root/nfs-vol1/dvd1
root@mesos002:~# convoy list
{
	"f210b3a2-bf40-4d5c-bd74-9e8b6666bb9a": {
		"UUID": "f210b3a2-bf40-4d5c-bd74-9e8b6666bb9a",
		"Name": "dvd1",
		"Driver": "vfs",
		"MountPoint": "/root/nfs-vol1/dvd1",
		"CreatedTime": "Wed Apr 06 13:05:59 +0800 2016",
		"DriverInfo": {
			"Driver": "vfs",
			"MountPoint": "/root/nfs-vol1/dvd1",
			"Path": "/root/nfs-vol1/dvd1",
			"PrepareForVM": "false",
			"Size": "0"
		},
		"Snapshots": {}
	}
}
root@mesos002:~# cat /proc/self/mountinfo  | grep dvd1
root@mesos002:~#
```

My question is why cannot I get the mount info from `/proc/self/mountinfo`? Thanks.

**Comment by yasker** [comment]
For VFS, the volume is not really "mounted". We simply created a directory under specified NFS directory and store volume there.

**Comment by jay-lau** [comment]
```
root@mesos002:~# convoy mount dvd1
/root/nfs-vol1/dvd1
root@mesos002:~# convoy list
{
    "f210b3a2-bf40-4d5c-bd74-9e8b6666bb9a": {
        "UUID": "f210b3a2-bf40-4d5c-bd74-9e8b6666bb9a",
        "Name": "dvd1",
        "Driver": "vfs",
        "MountPoint": "/root/nfs-vol1/dvd1",
        "CreatedTime": "Wed Apr 06 13:05:59 +0800 2016",
        "DriverInfo": {
            "Driver": "vfs",
            "MountPoint": "/root/nfs-vol1/dvd1",  <<<<<<
            "Path": "/root/nfs-vol1/dvd1",
            "PrepareForVM": "false",
            "Size": "0"
        },
        "Snapshots": {}
    }
}
```

You may see the `MountPoint` above, it is actually `mounted` as the volume cannot be deleted if I do not unmount it. So I think that there must be a mountpoint but I do not know where does this mount point in system's mountinfo, can you please help? Thanks.

**Comment by yasker** [comment]
You can simply do `convoy umount dvd1` before delete it.

**Comment by jay-lau** [comment]
Yes, but my question is how can I check the bind mount point from system's namespace view? Such as mountinfo etc.

**Comment by yasker** [comment]
In this case, it's not a real mount(or bind mount). It's more like a internal state of volume, say it's ready to use. So you cannot see it in mountinfo.

In the case of EBS or device mapper, you would see them in mount info.

**Comment by jay-lau** [comment]
Does there are any link can help me to test device mapper?

**Comment by jay-lau** [comment]
@yasker so you mean that the convoy handle different backend separately, for NFS, it does not bind mount actually; but for EBS or device mapper, it does bind mount, right? Does there are any document or test steps to help me to verify this? Thanks.

**Comment by jay-lau** [comment]
@yasker I found that the devicemapper works, thanks! But there is a question want to get your confirm, the following are my test steps

1) Test with unshare, the result is that mount point was always on the host but not in my namespace, do you know why?
No mount point in my namespace
```
root@devstack007:/home/gyliu# unshare -m /bin/bash
root@devstack007:/home/gyliu# convoy create dvd1
7f5cbdce-0343-4028-931c-84b486fa4678
root@devstack007:/home/gyliu# convoy mount dvd1
/var/lib/convoy/devicemapper/mounts/7f5cbdce-0343-4028-931c-84b486fa4678
root@devstack007:/home/gyliu# cat /proc/mounts | grep device
cgroup /sys/fs/cgroup/devices cgroup rw,relatime,devices 0 0
```
The mount point is actually on the host, but I DID run `convoy mount` in my namespace.
```
root@devstack007:/home/gyliu# cat /proc/mounts  | grep device
cgroup /sys/fs/cgroup/devices cgroup rw,relatime,devices 0 0
/dev/mapper/7f5cbdce-0343-4028-931c-84b486fa4678 /var/lib/convoy/devicemapper/mounts/7f5cbdce-0343-4028-931c-84b486fa4678 ext4 rw,relatime,stripe=512,data=ordered 0 0
```

**Comment by yasker** [comment]
Convoy inside container need to mount disk in the host filesystem, otherwise other Docker containers cannot access to it. So we can switch namespace for mount, see `mnt-ns` in https://github.com/rancher/convoy/blob/master/client/flags/flags.go .

All these are before Docker v1.10 share mount feature. Now it's possible to mount the volume to host without switch namespace.

**Comment by jay-lau** [comment]
@yasker , so from the description of `mnt-ns`, does it mean that I can generate a mountpoint inside a namespace? And the mountpoint will not be shared by other namespaces, right?

So for such case, the mountpoint will only be used by containers in the same namespace, right? Thanks.

**Comment by jay-lau** [comment]
From https://github.com/rancher/convoy/blob/master/util/util.go#L257-L281 , I can see that the `convoy` daemon will help generate the mount point, so it will depends on `convoy` daemon to decide where the mount point will be generated, right?

If the `convoy` is running on a host without `mnt-ns`, then it will generate monutpoint on host level; if the `convoy` is started with a `mnt-ns` flag, then it will only generate mount point inside the `mnt-ns`, right?

For my case, because the `convoy` daemon is running on host without `mnt-ns` flag, so even if I run the command `convoy mount` inside a unshare namespace, as it will call the `convoy` daemon running on the host, so the mount point will always be on the host but not in the namespace, right?

Sorry for so many questions, you really helped me a lot! Thanks @yasker
